module Boron
  class Compiler
    attr_reader :sources

    def initialize(expander: Expander.new, sources: SourceRegistry.new)
      @expander = expander
      @sources = sources
    end

    def lower(source, filename: "(string)")
      sources.add(filename, source)
      Lower.new.lower_all(@expander.expand_all(Reader.new(source, filename: filename).read_all))
    end

    def compile(source, filename: "(string)", standalone: false)
      prelude = standalone ? "require \"boron\"\nboron_env = Boron::Runtime.environment\n" : ""
      "# frozen_string_literal: true\n#{prelude}#{RubyEmitter.new.emit(lower(source, filename: filename))}\n"
    end
  end

  class Session
    attr_reader :environment, :sources

    def initialize
      @environment = Runtime.environment
      @sources = SourceRegistry.new
      @expander = Expander.new
    end

    def evaluate(source, filename: "(string)")
      boron_env = environment
      ruby = Compiler.new(expander: @expander, sources: sources).compile(source, filename: filename)
      # Execute the Ruby generated by Boron's typed IR emitter.
      Kernel.eval(ruby, binding, filename) # standard:disable Security/Eval
    end
  end
end
