module Boron
  class Compiler
    def lower(source, filename: "(string)")
      Lower.new.lower_all(Reader.new(source, filename: filename).read_all)
    end

    def compile(source, filename: "(string)", standalone: false)
      prelude = standalone ? "require \"boron\"\nboron_env = Boron::Runtime.environment\n" : ""
      "# frozen_string_literal: true\n#{prelude}#{RubyEmitter.new.emit(lower(source, filename: filename))}\n"
    end
  end

  class Session
    attr_reader :environment

    def initialize
      @environment = Runtime.environment
    end

    def evaluate(source, filename: "(string)")
      boron_env = environment
      ruby = Compiler.new.compile(source, filename: filename)
      # Execute the Ruby generated by Boron's typed IR emitter.
      Kernel.eval(ruby, binding, filename) # standard:disable Security/Eval
    end
  end
end
