source "https://rubygems.org"

gem "boron", path: "../.."
gem "activerecord", "~> 8.1.0"
gem "sqlite3", "~> 2.9"
gem "sinatra", "~> 4.2"
gem "rackup", "~> 2.0"
gem "puma", "~> 8.0"
gem "minitest", "~> 5.0", group: :test
